version: '3.4'

services:
  app:
    build:
      context: ./app
    command: "npm start"  
    volumes:
        - ./app/:/usr/src/app
        - /usr/src/app/node_modules

    ports:
      - 3006:3000
    env_file:
      - .env
    


